name: ci

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: fykosak/buildtools
          tags: |
            # minimal (short sha)
            type=sha
            # branch event
            type=ref,event=branch
            # tag event
            type=ref,event=tag
            type=match,pattern=(.*)\.(.*),group=1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=fykosak/buildtools:buildcache
          cache-to: type=registry,ref=fykosak/buildtools:buildcache,mode=max
